### ISSUE TITLE
After insertion it won't compile

### ISSUE THREAD

**Issue by lukazadel** [DJPorv/typed-elasticsearch#1]
the error as follows:

TSError: ? Unable to compile TypeScript
tools\manual_typings\project\elasticsearch.d.ts (6,5): 'constructor', which lacks return-type annotation,
implicitly has an 'any' return type. (7010)
    at getOutput (C:\RyanAir\rewardsService\node_modules\ts-node\src\ts-node.ts:209:13)
    at Object.loader (C:\RyanAir\rewardsService\node_modules\ts-node\src\ts-node.ts:224:23)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (C:\RyanAir\rewardsService\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\RyanAir\rewardsService\node_modules\liftoff\index.js:193:16)
    at module.exports (C:\RyanAir\rewardsService\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\RyanAir\rewardsService\node_modules\liftoff\index.js:185:9)

**Comment by DJPorv** [comment]
The typed elasticsearch is not quite finished yet, haven't had the time. But you could use the ambient one from @CasperSkydt 
install it like:

typings install github:CasperSkydt/DefinitelyTyped/elasticsearch/elasticsearch.d.ts --save --ambient
